### ISSUE TITLE
Unable to install `vue-devtools`

### ISSUE THREAD

**Issue by swanserquack** [swanserquack/TentaclesManager#9]
When running the project under the latest branch you get the following error:
Working on a fix right now
```
┏ Electron -------------------

  Unable to install `vue-devtools`:
   Error: Exited with code 9
      at ChildProcess.<anonymous> (/home/test/Desktop/TentaclesManager/node_modules/cross-unzip/index.js:38:21)
      at ChildProcess.emit (events.js:315:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

┗ ----------------------------
```

**Comment by swanserquack** [comment]
https://github.com/swanserquack/TentaclesManager/commit/4d33f8037dfcba99250b439fdb74a46baa2f1a89

**Comment by swanserquack** [comment]
That seems to be the cause of it, as mentioned in the commit I suspect a electron compatibility issue but will be working through it on the next few days.
